# Generated by Django 5.0.6 on 2026-07-02 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_visible_on_public',
            field=models.BooleanField(default=True, verbose_name="Ommaviy sahifada ko'rinish"),
        ),
    ]
