# Generated by Django 5.0.6 on 2026-07-18 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('youtube_id', models.CharField(blank=True, default='', help_text='YouTube video ID (masalan: dQw4w9WgXcQ)', max_length=100)),
                ('file', models.FileField(blank=True, help_text='Yuklangan MP4 video fayl', null=True, upload_to='marketing/videos/')),
                ('duration', models.CharField(default='5:00', help_text='Video davomiyligi (masalan: 5:30)', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('language', models.CharField(choices=[('uz', "O'zbek"), ('ru', 'Русский'), ('en', 'English')], default='uz', max_length=2)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Marketing video',
                'verbose_name_plural': 'Marketing videolar',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
