# Generated by Django 5.0.6 on 2026-07-17 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='meta_description',
            field=models.CharField(blank=True, help_text="Meta description (bo'sh bo'lsa excerpt ishlatiladi)", max_length=160),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='meta_title',
            field=models.CharField(blank=True, help_text="SEO title (bo'sh bo'lsa post title ishlatiladi)", max_length=70),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='og_image',
            field=models.ImageField(blank=True, help_text="Open Graph rasm (bo'sh bo'lsa featured_image ishlatiladi)", null=True, upload_to='blog/og/'),
        ),
    ]
