# Generated by Django 5.0.6 on 2026-06-21 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='Biznesingiz Bandlovlarini Avtomatlashtiring', help_text='Marketing sahifasi bosh sarlavhasi', max_length=300)),
                ('hero_subtitle', models.TextField(default="Xizmat ko'rsatuvchi bizneslar uchun eng oddiy navbat tizimi.", help_text='Marketing sahifasi taglavhasi')),
                ('starter_price', models.PositiveIntegerField(default=0, help_text='Starter plan narxi (UZS/oy)')),
                ('growth_price_monthly', models.PositiveIntegerField(default=99000, help_text='Growth plan oylik narxi (UZS)')),
                ('growth_price_yearly', models.PositiveIntegerField(default=79000, help_text='Growth plan yillik narxi (UZS/oy)')),
                ('enterprise_price_monthly', models.PositiveIntegerField(default=249000, help_text='Enterprise plan oylik narxi (UZS)')),
                ('enterprise_price_yearly', models.PositiveIntegerField(default=199000, help_text='Enterprise plan yillik narxi (UZS/oy)')),
                ('stats_uptime', models.CharField(default='99.9%', help_text="Uptime ko'rsatkichi", max_length=20)),
                ('stats_appointments', models.CharField(default='20,000+', help_text='Jami bandlovlar soni', max_length=50)),
                ('stats_businesses', models.CharField(default='500+', help_text='Faol bizneslar soni', max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
