# Generated by Django 5.0.6 on 2026-06-29 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='contact_email',
            field=models.CharField(default='support@booksaas.com', help_text='Aloqa email manzili', max_length=150),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_phone',
            field=models.CharField(default='+998 90 123 45 67', help_text='Aloqa telefon raqami', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_telegram',
            field=models.CharField(default='https://t.me/BookSaaSBot', help_text='Telegram bot yoki guruh havolasi', max_length=150),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='logo',
            field=models.ImageField(blank=True, help_text='Sayt logotipi (Oq/shaffof tavsiya etiladi)', null=True, upload_to='site_logos/'),
        ),
    ]
