# Generated by Django 5.0.6 on 2026-06-30 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0002_sitesettings_contact_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='payment_card_holder',
            field=models.CharField(default='SUPER ADMIN', help_text='Karta egasining ismi familyasi', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='payment_card_number',
            field=models.CharField(default='9860 0101 2345 6789', help_text="Karta raqami (to'lov uchun)", max_length=50),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='enterprise_price_monthly',
            field=models.PositiveIntegerField(default=249000, help_text='Max plan oylik narxi (UZS)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='enterprise_price_yearly',
            field=models.PositiveIntegerField(default=199000, help_text='Max plan yillik narxi (UZS/oy)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='growth_price_monthly',
            field=models.PositiveIntegerField(default=99000, help_text='Pro plan oylik narxi (UZS)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='growth_price_yearly',
            field=models.PositiveIntegerField(default=79000, help_text='Pro plan yillik narxi (UZS/oy)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='starter_price',
            field=models.PositiveIntegerField(default=0, help_text='Start plan narxi (UZS/oy)'),
        ),
    ]
