# Generated by Codex on 2026-07-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0003_sitesettings_payment_card_holder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='marketing_content',
            field=models.JSONField(blank=True, default=dict, help_text='Marketing sahifalari matnlari. Kalitlar: uz, ru, en.'),
        ),
    ]
