# Generated by Django 5.0.6 on 2026-07-07 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0004_sitesettings_marketing_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='contact_email',
            field=models.CharField(default='support@BookFlow.com', help_text='Aloqa email manzili', max_length=150),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='contact_telegram',
            field=models.CharField(default='https://t.me/BookFlowBot', help_text='Telegram bot yoki guruh havolasi', max_length=150),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo',
            field=models.ImageField(blank=True, help_text='Sayt logotipi', null=True, upload_to='site_logos/'),
        ),
    ]
