# Generated by Django 5.0.6 on 2026-07-09 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0004_sitesettings_marketing_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Tarif nomi (masalan: Start, Pro, Max)', max_length=50)),
                ('slug', models.SlugField(help_text='Sistemadagi ID (masalan: free, growth, enterprise)', max_length=20, unique=True)),
                ('description', models.CharField(blank=True, help_text="Qisqacha ta'rif", max_length=200)),
                ('price_monthly', models.PositiveIntegerField(default=0, help_text="Oylik to'lov summasi (UZS)")),
                ('price_yearly', models.PositiveIntegerField(default=0, help_text="Yillik to'lovda bir oy uchun summa (UZS)")),
                ('max_employees', models.IntegerField(blank=True, help_text="Maksimal xodimlar soni (Bo'sh bo'lsa cheksiz)", null=True)),
                ('max_appointments_monthly', models.IntegerField(blank=True, help_text="Oylik maksimal bandlovlar (Bo'sh bo'lsa cheksiz)", null=True)),
                ('allow_telegram', models.BooleanField(default=False, help_text='Telegram xabarnomalar va bot')),
                ('allow_email', models.BooleanField(default=True, help_text='Email xabarnomalar')),
                ('allow_custom_domain', models.BooleanField(default=False, help_text='Shaxsiy domen ulash imkoniyati')),
                ('allow_branding', models.BooleanField(default=False, help_text='Shaxsiy brending (Logotip va hk)')),
                ('allow_custom_css', models.BooleanField(default=False, help_text='Custom CSS imkoniyati')),
                ('allow_api', models.BooleanField(default=False, help_text='API va Webhooklar')),
                ('is_active', models.BooleanField(default=True, help_text="Aktiv tarif (Saytda ko'rinadi)")),
                ('is_popular', models.BooleanField(default=False, help_text='Tavsiya etiladigan tarif belgisi (Mashhur)')),
                ('order', models.PositiveIntegerField(default=0, help_text='Tartib raqami (kichigi oldin chiqadi)')),
            ],
            options={
                'verbose_name': 'Pricing Plan',
                'verbose_name_plural': 'Pricing Plans',
                'ordering': ['order'],
            },
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='contact_email',
            field=models.CharField(default='support@BookFlow.com', help_text='Aloqa email manzili', max_length=150),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='contact_telegram',
            field=models.CharField(default='https://t.me/BookFlowBot', help_text='Telegram bot yoki guruh havolasi', max_length=150),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo',
            field=models.ImageField(blank=True, help_text='Sayt logotipi', null=True, upload_to='site_logos/'),
        ),
        migrations.CreateModel(
            name='PricingPlanFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text="Funksiya matni (Masalan: 'Cheksiz qabullar')", max_length=200)),
                ('is_included', models.BooleanField(default=True, help_text="Ushbu tarifda bor yoki yo'q (chizib ko'rsatish uchun)")),
                ('order', models.PositiveIntegerField(default=0, help_text="Ro'yxatdagi tartib raqami")),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='superadmin.pricingplan')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
