# Generated by Django 5.0.6 on 2026-07-10 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0005_pricingplan_alter_sitesettings_contact_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingplan',
            name='allow_google_calendar',
            field=models.BooleanField(default=False, help_text='Google Calendar sinxronizatsiyasi'),
        ),
    ]
