# Generated by Django 5.0.6 on 2026-07-10 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0005_alter_sitesettings_contact_email_and_more'),
        ('superadmin', '0005_pricingplan_alter_sitesettings_contact_email_and_more'),
    ]

    operations = [
    ]
