# Generated by Django 5.0.6 on 2026-07-12 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0006_pricingplan_allow_google_calendar'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingplan',
            name='allow_white_label',
            field=models.BooleanField(default=False, help_text='White Label (BookFlow brendini yashirish)'),
        ),
    ]
