# Generated by Django 5.0.6 on 2026-07-13 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0006_merge_20260710_2043'),
        ('superadmin', '0007_add_max_features'),
    ]

    operations = [
    ]
