# Generated by Django 5.0.6 on 2026-07-13 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0014_api_key_date'),
        ('superadmin', '0007_add_max_features'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessSubscription',
            fields=[
            ],
            options={
                'verbose_name': 'Obuna',
                'verbose_name_plural': 'Obunalar',
                'permissions': [('manage_subscriptions', 'Obunalarni boshqarish'), ('view_subscription_stats', "Obuna statistikasini ko'rish")],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('business.business',),
        ),
    ]
