# Generated by Django 5.0.6 on 2026-07-13 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0008_businesssubscription'),
        ('superadmin', '0008_merge_0006_merge_20260710_2043_0007_add_max_features'),
    ]

    operations = [
    ]
