# Generated by Django 5.0.6 on 2026-07-15 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0009_merge_20260713_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='logo_light',
            field=models.ImageField(blank=True, help_text="Sayt logotipi (yorug'/light rejim uchun). Bo'sh qoldirilsa, dark logo ishlatiladi.", null=True, upload_to='site_logos/'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo',
            field=models.ImageField(blank=True, help_text="Sayt logotipi (qorong'i/dark rejim uchun)", null=True, upload_to='site_logos/'),
        ),
    ]
