# Generated by Django 5.0.6 on 2026-07-17 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0010_add_logo_light_to_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingplan',
            name='allow_advanced_seo',
            field=models.BooleanField(default=False, help_text='Advanced SEO (sitemap, schema.org, JSON-LD, OG teglar)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='default_meta_description',
            field=models.CharField(blank=True, default="Online band qilish tizimi. Xizmat ko'rsatuvchi bizneslar uchun onlayn qabul, xodimlar jadvali va mijozlar bazasi.", help_text="Global default meta description (agar business/ post da bo'lmasa)", max_length=160),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='default_og_image',
            field=models.ImageField(blank=True, help_text="Global default OG Image (agar businessda bo'lmasa)", null=True, upload_to='site/og/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='google_site_verification',
            field=models.CharField(blank=True, help_text='Google Search Console verification code', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='yandex_verification',
            field=models.CharField(blank=True, help_text='Yandex Webmaster verification code', max_length=100),
        ),
    ]
