# Generated by Django 5.0.6 on 2026-07-24 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0011_pricingplan_allow_advanced_seo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='favicon',
            field=models.ImageField(blank=True, help_text='Sayt favikoni (32x32 yoki 64x64 .png, .ico, .svg)', null=True, upload_to='site_logos/'),
        ),
    ]
