# Generated by Django 5.0.6 on 2026-07-24 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0012_sitesettings_favicon'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingplan',
            name='price_3months',
            field=models.PositiveIntegerField(default=0, help_text='3 oylik umumiy narx (UZS). Masalan: 250 000'),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='yearly_badge',
            field=models.CharField(blank=True, default='', help_text="Yillik tanlanganda badge matni. Masalan: '🎁 2 oy bepul' yoki '25% tejaysiz'", max_length=50),
        ),
        migrations.AlterField(
            model_name='pricingplan',
            name='price_monthly',
            field=models.PositiveIntegerField(default=0, help_text="Oylik to'lov summasi (UZS) — eski, hozir ishlatilmaydi"),
        ),
        migrations.AlterField(
            model_name='pricingplan',
            name='price_yearly',
            field=models.PositiveIntegerField(default=0, help_text='1 yillik umumiy narx (UZS). Masalan: 900 000'),
        ),
    ]
