# Generated by Django 5.0.6 on 2026-07-24 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0013_price_3months_yearly_badge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricingplan',
            name='price_3months',
        ),
        migrations.RemoveField(
            model_name='pricingplan',
            name='price_yearly',
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='discount_3months',
            field=models.PositiveIntegerField(default=0, help_text='3 oylik chegirma foizi (0–100%). Masalan: 10 → 10% chegirma'),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='discount_yearly',
            field=models.PositiveIntegerField(default=0, help_text='1 yillik chegirma foizi (0–100%). Masalan: 20 → 20% chegirma'),
        ),
        migrations.AlterField(
            model_name='pricingplan',
            name='price_monthly',
            field=models.PositiveIntegerField(default=0, help_text='Asosiy oylik narx (UZS). Masalan: 99 000'),
        ),
        migrations.AlterField(
            model_name='pricingplan',
            name='yearly_badge',
            field=models.CharField(blank=True, default='', help_text="Yillik tanlanganda badge matni. Bo'sh qolsa chegirma % dan avtomatik to'ldiriladi. Masalan: '🎁 2 oy bepul'", max_length=50),
        ),
    ]
