# Generated by Django 5.0.6 on 2026-06-13 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='telegram_connect_token',
            field=models.CharField(blank=True, help_text='One-time token used in the bot /start deep link', max_length=64),
        ),
        migrations.AlterField(
            model_name='business',
            name='instagram',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='business',
            name='telegram',
            field=models.CharField(blank=True, help_text='Telegram username for public display', max_length=100),
        ),
        migrations.AlterField(
            model_name='business',
            name='telegram_chat_id',
            field=models.CharField(blank=True, help_text='Auto-filled when business owner connects via bot', max_length=50),
        ),
        migrations.AlterField(
            model_name='business',
            name='telegram_notifications_enabled',
            field=models.BooleanField(default=False, help_text='Send booking notifications to Telegram'),
        ),
    ]
