# Generated by Django 5.0.6 on 2026-06-21 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_business_telegram_connect_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='is_blocked',
            field=models.BooleanField(default=False, help_text='Admin tomonidan bloklangan biznes dashboardga kira olmaydi'),
        ),
        migrations.AddField(
            model_name='business',
            name='subscription_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='subscription_plan',
            field=models.CharField(choices=[('free', 'Free / Starter'), ('growth', 'Growth'), ('enterprise', 'Enterprise')], default='free', max_length=20),
        ),
        migrations.AddField(
            model_name='business',
            name='subscription_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='subscription_status',
            field=models.CharField(choices=[('trial', 'Trial'), ('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='trial', max_length=20),
        ),
    ]
