# Generated by Django 5.0.6 on 2026-06-27 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_business_is_blocked_business_subscription_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='custom_css',
            field=models.TextField(blank=True, help_text='Maxsus CSS (faqat Korporativ tarif)'),
        ),
        migrations.AddField(
            model_name='business',
            name='primary_color',
            field=models.CharField(default='#6366f1', help_text='Public sahifa asosiy rangi (hex masalan #6366f1)', max_length=7),
        ),
        migrations.AddField(
            model_name='business',
            name='welcome_text',
            field=models.CharField(blank=True, help_text='Public sahifadagi salomlashish matni', max_length=300),
        ),
    ]
