# Generated by Django 5.0.6 on 2026-06-27 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_business_custom_css_business_primary_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='welcome_text',
        ),
        migrations.AddField(
            model_name='business',
            name='banner_image',
            field=models.ImageField(blank=True, help_text='Public sahifa banner rasmi (pullik tariflar uchun)', null=True, upload_to='business/banners/'),
        ),
    ]
