# Generated by Django 5.0.6 on 2026-06-27 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_remove_business_welcome_text_business_banner_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='button_style',
            field=models.CharField(choices=[('rounded', 'Yumaloq (Rounded)'), ('square', "To'rtburchak (Square)"), ('pill', 'Pill shaklida')], default='rounded', help_text='Tugmalar shakli', max_length=20),
        ),
        migrations.AddField(
            model_name='business',
            name='card_shadow',
            field=models.CharField(choices=[('light', 'Yengil'), ('medium', "O'rtacha"), ('strong', 'Kuchli')], default='medium', help_text='Kartochkalar soyasi', max_length=20),
        ),
    ]
