# Generated by Django 5.0.6 on 2026-06-30 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0006_business_button_style_business_card_shadow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='subscription_plan',
            field=models.CharField(choices=[('free', 'Start'), ('growth', 'Pro'), ('enterprise', 'Max')], default='free', max_length=20),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('pro', 'Pro'), ('max', 'Max')], max_length=20)),
                ('amount', models.PositiveIntegerField(help_text="To'lov summasi (UZS)")),
                ('receipt', models.FileField(help_text='Chek rasmi', upload_to='payments/receipts/')),
                ('note', models.TextField(blank=True, help_text='Foydalanuvchi izohi')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('approved', 'Tasdiqlangan'), ('rejected', 'Bekor qilingan')], default='pending', max_length=20)),
                ('rejected_reason', models.TextField(blank=True, help_text='Rad etish sababi (superadmin)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='business.business')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
