# Generated by Django 5.0.6 on 2026-07-02 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0007_alter_business_subscription_plan_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='navbar_style',
            field=models.CharField(choices=[('classic', 'Klassik'), ('glass', 'Glass (Shaffof)'), ('premium', 'Premium')], default='classic', help_text='Sahifa menyusi uslubi (pullik tariflar uchun)', max_length=20),
        ),
        migrations.AlterField(
            model_name='business',
            name='custom_css',
            field=models.TextField(blank=True, help_text='Maxsus CSS (faqat Max tarif)'),
        ),
        migrations.AlterField(
            model_name='business',
            name='subscription_status',
            field=models.CharField(choices=[('trial', 'Sinov'), ('active', 'Faol'), ('expired', 'Muddati tugagan'), ('cancelled', 'Bekor qilingan')], default='trial', max_length=20),
        ),
    ]
