# Generated by Django 5.0.6 on 2026-07-02 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0008_business_navbar_style_alter_business_custom_css_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='navbar_style',
            field=models.CharField(choices=[('glass', 'Glass Ultra — Vision Pro uslubi'), ('minimal', 'Minimal Luxury — Linear uslubi'), ('modern', 'Modern Creative — Framer uslubi')], default='glass', help_text='Sahifa menyusi uslubi (pullik tariflar uchun)', max_length=20),
        ),
    ]
