# Generated by Django 5.0.6 on 2026-07-04 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0009_alter_business_navbar_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='custom_domain',
            field=models.CharField(blank=True, help_text='Masalan: booking.meningklinikam.uz', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='business',
            name='domain_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='business',
            name='domain_verify_token',
            field=models.CharField(blank=True, default='', help_text='DNS TXT record uchun token (avtomatik generatsiya qilinadi)', max_length=64),
        ),
    ]
