# Generated by Django 5.0.6 on 2026-07-08 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0010_business_custom_domain_business_domain_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Joylashuv kengligi (xarita orqali kiritiladi)', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Joylashuv uzunligi (xarita orqali kiritiladi)', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='show_in_directory',
            field=models.BooleanField(default=False, help_text="Marketing sahifasidagi bizneslar ro'yxatida ko'rsatish"),
        ),
    ]
