# Generated by Django 5.0.6 on 2026-07-10 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0011_location_and_directory'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='google_calendar_id',
            field=models.CharField(blank=True, default='primary', help_text='Google Calendar ID (default: primary)', max_length=200),
        ),
        migrations.AddField(
            model_name='business',
            name='google_calendar_sync_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='business',
            name='google_credentials',
            field=models.JSONField(blank=True, help_text='Google OAuth credentials (token, refresh_token, etc)', null=True),
        ),
    ]
