# Generated by Django 5.0.6 on 2026-07-12 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0012_business_google_calendar_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='api_key',
            field=models.CharField(blank=True, default='', help_text='API kaliti (avtomatik generatsiya)', max_length=64),
        ),
        migrations.AddField(
            model_name='business',
            name='webhook_url',
            field=models.URLField(blank=True, default='', help_text='Webhook URL manzili'),
        ),
        migrations.AddField(
            model_name='business',
            name='white_label_enabled',
            field=models.BooleanField(default=False, help_text='White Label (BookFlow brendi yashirish)'),
        ),
    ]
