# Generated by Django 5.0.6 on 2026-07-12 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0013_add_max_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='api_key_created',
            field=models.DateTimeField(blank=True, help_text='API kaliti yaratilgan vaqt', null=True),
        ),
    ]
