# Generated by Django 5.0.6 on 2026-07-16 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0014_api_key_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRCodeScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('referrer', models.CharField(blank=True, default='', max_length=500)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_scans', to='business.business')),
            ],
            options={
                'verbose_name': 'QR Code Scan',
                'verbose_name_plural': 'QR Code Scans',
                'ordering': ['-scanned_at'],
                'indexes': [models.Index(fields=['business', 'scanned_at'], name='business_qr_busines_12b860_idx')],
            },
        ),
    ]
