# Generated by Django 5.0.6 on 2026-07-17 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0015_qrcodescan'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Meta description (bo\'sh bo\'lsa "about" ishlatiladi)', max_length=160),
        ),
        migrations.AddField(
            model_name='business',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='Meta keywords (vergul bilan ajrating)', max_length=255),
        ),
        migrations.AddField(
            model_name='business',
            name='meta_title',
            field=models.CharField(blank=True, help_text="SEO title (bo'sh bo'lsa biznes nomi ishlatiladi)", max_length=70),
        ),
        migrations.AddField(
            model_name='business',
            name='og_image',
            field=models.ImageField(blank=True, help_text='Open Graph rasm (link yuborilganda chiqadi)', null=True, upload_to='business/og/'),
        ),
    ]
