# Generated by Django 5.0.6 on 2026-07-24 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0016_business_meta_description_business_meta_keywords_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='duration',
            field=models.CharField(choices=[('3months', '3 oylik (90 kun)'), ('yearly', '1 yillik (365 kun)')], default='3months', help_text='Obuna davomiyligi: 3 oylik yoki 1 yillik', max_length=20),
        ),
    ]
