# Generated by Django 5.0.6 on 2026-07-29 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0017_payment_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='plan',
            field=models.CharField(help_text='Tarif slug (masalan: growth, enterprise)', max_length=50),
        ),
    ]
