# Generated by Django 5.0.6 on 2026-07-10 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_appointment_doctor_notes_alter_appointment_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='google_event_id',
            field=models.CharField(blank=True, help_text='Google Calendar event ID', max_length=200),
        ),
    ]
